In [25]:
import numpy as np
import tensorflow as tf
import json
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, LSTM, Dense, Concatenate

In [32]:
# Exemple de séries temporelles pour plusieurs joueurs
with open('time_on_ice_data.json', 'r') as f:
    time_on_ice = json.load(f)

# Trouver la longueur maximale des séries temporelles pour faire du padding
max_length = max([len(player['past']) for player in time_on_ice.values()])

# Separer en training/testing

# Convertir le dictionnaire time_on_ice en une liste de tuples (clé, valeur)
time_on_ice_items = list(time_on_ice.items())

# Séparer en ensemble d'entraînement et de test (80% training, 20% testing)
train_data, test_data = train_test_split(time_on_ice_items, test_size=0.01, random_state=42)

# Reconvertir les ensembles en dictionnaires
train_dict = dict(train_data)
test_dict = dict(test_data)

# Afficher la taille de chaque ensemble
print(f"Taille de l'ensemble d'entraînement : {len(train_dict)}")
print(f"Taille de l'ensemble de test : {len(test_dict)}")

Taille de l'ensemble d'entraînement : 148
Taille de l'ensemble de test : 2
Taille de l'ensemble d'entraînement : 148
Taille de l'ensemble de test : 2


In [33]:
# Extraire les cibles et les variables fixes (âge, grandeur)
targets = np.array([player['target'] for player in train_dict.values()])
ages = np.array([player['age'] for player in train_dict.values()])
heights = np.array([player['height'] for player in train_dict.values()])

targets

array([20, 15, 18, 17, 12,  8, 17,  6, 13,  8, 14, 17, 11, 16,  7, 13, 10,  7,  2,  5,
        7,  1, 14, 19,  9,  5, 18, 18,  6,  6, 17, 15,  8, 11,  2,  9, 16, 13, 19, 10,
       19,  7,  1, 12, 12, 12, 17,  9, 16, 17, 15, 20, 12,  7, 16, 17, 18,  8, 12, 10,
        5, 11,  8, 15, 15, 14, 15, 13,  3, 19,  5,  7, 14,  4, 11, 10, 14,  3, 12, 12,
       14,  5,  1,  5,  7, 12, 16,  3, 12, 13, 12, 16, 12,  9, 16,  9,  5, 19,  4,  6,
       12,  7, 12, 12,  4, 18,  8, 14,  2, 14, 10,  3,  8, 17, 19,  5,  7, 12,  9,  8,
       11, 11,  4,  6,  9, 20, 16, 11, 15,  3,  4, 15,  7, 14,  9,  9,  4, 17,  4, 15,
       15,  5,  7, 10, 13, 10, 15,  7])

In [34]:
# Padding des séries temporelles pour qu'elles aient toutes la même longueur
padded_series = [
    [0] * (max_length - len(player['past'])) + player['past']
    for player in train_dict.values()
]

# Transformer les données en matrices (entrée pour le LSTM)
X_time_series = np.array(padded_series).reshape(len(train_dict), max_length, 1)
X_fixed = np.column_stack((ages, heights))  # Variables fixes

In [35]:
# Définir les dimensions
num_players = len(train_dict)  # Nombre de joueurs (3 dans cet exemple)
num_fixed_features = X_fixed.shape[1]  # Nombre de variables fixes (2 ici: âge, grandeur)

# Définir les entrées pour le modèle LSTM
input_time_series = Input(shape=(max_length, 1), name="time_series_input")
input_fixed = Input(shape=(num_fixed_features,), name="fixed_input")

In [36]:
# LSTM pour les séries temporelles
lstm_output = LSTM(units=50, activation='relu')(input_time_series)

# Combiner la sortie du LSTM avec les variables fixes
combined = Concatenate()([lstm_output, input_fixed])

# Ajouter une couche dense pour la prédiction finale
output = Dense(1)(combined)

In [37]:
# Définir et compiler le modèle
model = Model(inputs=[input_time_series, input_fixed], outputs=output)
model.compile(optimizer='adam', loss='mse')

In [38]:
# Afficher le résumé du modèle
model.summary()

Model: "functional_1"
Model: "functional_1"


┏━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)          ┃ Output Shape        ┃     Param # ┃ Connected to        ┃
┡━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━┩
│ time_series_input     │ (None, 10, 1)       │           0 │ -                   │
│ (InputLayer)          │                     │             │                     │
├───────────────────────┼─────────────────────┼─────────────┼─────────────────────┤
│ lstm_1 (LSTM)         │ (None, 50)          │      10,400 │ time_series_input[… │
├───────────────────────┼─────────────────────┼─────────────┼─────────────────────┤
│ fixed_input           │ (None, 2)           │           0 │ -                   │
│ (InputLayer)          │                     │             │                     │
├───────────────────────┼─────────────────────┼─────────────┼─────────────────────┤
│ concatenate_1         │ (None, 52)          │           0 │ lstm_1[0][0], 

 Total params: 10,453 (40.83 KB)
 Total params: 10,453 (40.83 KB)


 Trainable params: 10,453 (40.83 KB)
 Trainable params: 10,453 (40.83 KB)


 Non-trainable params: 0 (0.00 B)
 Non-trainable params: 0 (0.00 B)


In [ ]:
# Entraîner le modèle avec les données
model.fit([X_time_series, X_fixed], targets, epochs=100, batch_size=1)

In [42]:
# Padding des séries temporelles pour qu'elles aient toutes la même longueur
padded_series_test = [
    [0] * (max_length - len(player['past'])) + player['past']
    for player in test_dict.values()
]
ages = np.array([player['age'] for player in test_dict.values()])
heights = np.array([player['height'] for player in test_dict.values()])

# Transformer les données en matrices (entrée pour le LSTM)
X_time_series_test = np.array(padded_series_test).reshape(len(test_dict), max_length, 1)
X_fixed_test = np.column_stack((ages, heights))  # Variables fixes

# Faire des prédictions après l'entraînement
predictions = model.predict([X_time_series_test, X_fixed_test])
print(X_time_series_test[1])
print("Prediction:", predictions[1])


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step


[[17]
 [17]
 [11]
 [11]
 [ 4]
 [12]
 [ 7]
 [14]
 [11]
 [ 7]]
Prediction: [10.150367]
[[17]
 [17]
 [11]
 [11]
 [ 4]
 [12]
 [ 7]
 [14]
 [11]
 [ 7]]
Prediction: [10.150367]
